<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        (function(root, factory){
            if (typeof define === 'function' && define.amd) {
                require(["ace"], factory);
            } else {
                factory(root.ace);
            }
        })(this, function(ace) {
            try {
                ace.settings.check('breadcrumbs', 'fixed')
            } catch (e) {
                console.log(e)
            }
        })
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>
        <li>
        <a href="/admin/option/index">Option</a>
        </li>
        <?if(empty($item->id)):?>
        <li class="">Create New Option</li>
        <?else:?>
        <li class="active">Edit Option</li>
        <?endif?>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>
<form id="" action="" method="POST" enctype="multipart/form-data" novalidate="novalidate">
    <?=$form->render('id')?>
    <div class="page-content">
        <div class="page-header">
            <?if(empty($item->id)):?>
            <h1>Create New Option</h1>
            <?else:?>
            <h1>Edit Option</h1>
            <?endif?>
        </div><!-- /.page-header -->

        <div class="row">
            <div class="col-xs-9">
                <!-- PAGE CONTENT BEGINS -->

                <div class="form-group">
                    <label class="block clearfix">
                        配置名称
                        <?=$form->render('optionName', array(
                            'class' => 'form-control input-lg',
                            'placeholder' => 'optionName',
                            'required' => 'required',
                        ))?>
                    </label>
                </div>
                <div class="form-group">
                    <label class="block clearfix">
                        配置值
                        <?=$form->render('optionValue', array(
                            'class' => 'form-control input-lg',
                            'placeholder' => 'optionValue',
                        ))?>
                    </label>
                </div>
                <div class="form-group">
                    <div class="widget-box transparent">
                        <div class="widget-header">
                            <h4 class="lighter">注释</h4>
                            <div class="widget-toolbar no-border ">
                                <div class="btn-group">
                                </div>
                            </div>
                        </div><!--widget box header-->
                    </div><!--widget box end-->

                    <label class="block clearfix">

                        <div class="markdown-editor">
                            <?=$form->render('optionComment', array(
                                'class' => 'form-control',
                                //'class' => 'form-control wysiwyg',
                                'rows' => 12,
                            ))?>
                        </div>
                        <!--
                        <button id="test">test</button>
                        -->
                    </label>
                </div>

                <div class="form-group">
                </div>

            </div><!-- /.col -->
            <div class="col-xs-3">

                <div class="widget-box">
                    <div class="widget-header widget-header-small">
                        <h5 class="lighter">Publish</h5>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-up"></i>
                            </a>
                        </span>
                    </div>
                    <div class="widget-body">
                        <div class="widget-main">
                        </div>
                        <div class="clearfix form-actions no-margin">
                            <input name="__redirect" type="hidden" value="" />
                            <button type="submit" class="btn form-submiter" data-change-name="status" data-change-value="draft">
                                <i class="icon-save"></i>
                                Save Draft
                            </button>
                            <button type="submit" class="btn btn-info form-submiter" data-change-name="status" data-change-value="published">
                                <i class="icon-ok"></i>
                                Publish
                            </button>
                        </div>
                    </div>
                </div><!--widgex box-->


                <div class="hr hr-double dotted"></div>
                <div class="widget-box collapsed">
                    <div class="widget-header widget-header-small">
                        <h5 class="lighter">Publish Time</h5>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-down"></i>
                            </a>
                        </span>
                    </div>

                    <div class="widget-body">
                        <div class="widget-main">
                            <div class="input-group">
                                <input name="day" type="text" data-date-format="yyyy-mm-dd" class="form-control date-picker" value="<?=empty($item->createdAt) ? '' : $this->tag->datetime($item->createdAt, 'Y-m-d')?>">
                                <span class="input-group-addon">
                                    <i class="icon-calendar bigger-110"></i>
                                </span>
                            </div>
                            <div class="input-group bootstrap-timepicker">
                                <input name="time" type="text" class="form-control time-picker" value="<?=empty($item->createdAt) ? '' : $this->tag->datetime($item->createdAt, 'H:i:s')?>">
                                <span class="input-group-addon">
                                    <i class="icon-time bigger-110"></i>
                                </span>
                                <?=$form->render('createdAt', array(
                                ))?>
                            </div>
                        </div>
                    </div>
                </div><!--widgex box-->

                <div class="hr hr-double dotted"></div>

            </div><!-- /.col -->

        </div><!-- /.row -->
    </div><!-- /.page-content -->
</form>

<script>
    (function(root, factory){
        if (typeof define === 'function' && define.amd) {
            require(["moment", "jquery"], factory);
        } else {
            factory(root.moment, root.jQuery);
        }
    })(this, function(moment, $) {
        $(document).ready(function () {
            var updateCreateTime = function () {
                var day = $('input[name=day]').val();
                var time = $('input[name=time]').val();
                time = time.length == 7 ? '0' + time : time;
                var timestamp = moment(day + ' ' + time).format('X');
                $('input[name=createdAt]').val(timestamp);
            }
            $('input[name=day], input[name=time]').on('change', updateCreateTime);
        });
    })
</script>
