<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try {
            ace.settings.check('breadcrumbs', 'fixed')
        } catch (e) {
        }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/dashboard">Home</a>
        </li>

        <li>
            <a href="/admin/block/index">Page Block</a>
        </li>
        <li class="active">
            <? if (empty($item->name)): ?>
                Create
            <? else: ?>
                Edit
            <?endif ?>
        </li>
    </ul>
    <!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <!--
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
        -->
    </div>
    <!-- #nav-search -->
</div>

<form id="" action="" method="POST" enctype="multipart/form-data" novalidate="novalidate">
    <div class="page-content">
        <div class="page-header">
            <? if (empty($item->name)): ?>
                <h1>Create New Page Block <small class="text-muted">当添加新的页面区块后，将 name 告诉工程师即可，以后便可以在后台动态修改。Tell the name to our Engineer after the Block added.</small></h1>
            <? else: ?>
                <h1>Edit Page Block</h1>
            <?endif ?>
        </div>
        <!-- /.page-header -->

        <div class="row">
            <div class="col-xs-12">
                <!-- PAGE CONTENT BEGINS -->
                <div class="form-group">
                    <div class="widget-box transparent">
                        <div class="widget-header">
                            <h4 class="lighter">Name <small class="text-muted">NOTE: name of blocks must be unique.</small></h4>
                        </div>
                        <!--widget box header-->

                    </div>
                    <!--widget box end-->

                    <label class="block clearfix">
                        <div>
                            <?=
                            $form->render(
                                'name',
                                array(
                                    'class' => 'form-control',
                                    //'class' => 'form-control wysiwyg',
                                    'required' => 'required',
                                    'maxLength' => 30
                                )
                            )?>
                        </div>
                    </label>
                </div>
                <div class="form-group">
                    <div class="widget-box transparent">
                        <div class="widget-header">
                            <h4 class="lighter">Content</h4>
                            <div class="widget-toolbar no-border ">
                                <div class="btn-group">
                                    <button class="btn btn-sm btn-info editor-open-media-handle">
                                        <i class="icon-plus align-top bigger-125"></i>
                                        Select Media
                                    </button>

                                    <span class="btn btn-sm btn-purple fileinput-button">
                                        <i class="icon-cloud-upload align-top bigger-125"></i>
                                        Upload Media
                                        <input type="file" multiple  class="editor-upload-handle" data-connect-editor=".editor-content" />
                                    </span>

                                    <ul id="switch-code" class="nav nav-tabs hide">
                                        <li class="">
                                            <a href="#format-markdown" data-toggle="tab">Markdown</a>
                                        </li>
                                        <li>
                                            <a href="#format-html" data-toggle="tab">Html</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!--widget box header-->
                    </div>
                    <!--widget box end-->

                    <label class="block clearfix">

                        <div id="epiceditor"  class="markdown-editor">
                            <?=
                            $form->render(
                                'content',
                                array(
                                    'class' => 'form-control editor editor-content',
                                    'rows' => 12,
                                    'required' => 'required',
                                )
                            )?>
                        </div>
                    </label>
                </div>

                <div class="form-action">
                    <button class="btn btn-primary">Submit</button>
                </div>
            </div>
            <!-- /.col -->


        </div>
        <!-- /.row -->
    </div>
    <!-- /.page-content -->
</form>
