<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/dashboard">Home</a>
        </li>

        <li>
            <a href="/admin/useraudit" class="active">User Operation Log</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
                User Operation Log
<!--                <a href="/admin/user/create" class="btn btn-sm"><i class="icon-user align-top bigger-125"></i> Create New</a>-->
            </h3>
            <div class="table-header">
                Showing <?=$pager->offset_start?> to <?=$pager->offset_end?> of <?=$pager->total_items?> Items
            </div>

            <div class="table-responsive dataTables_wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-inline">
                            操作名称
                            <div class="form-group">
                                <?= $form->render('operationName', array(
                                    'class' => 'form-control input-sm'
                                )) ?>
                            </div>
                            判定规则
                            <div class="form-group">
                                <?= $form->render('spamReason', array(
                                    'class' => 'form-control input-sm'
                                )) ?>
                            </div>
                            <div class="form-group">
                                <?=$form->render('limit', array(
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>
                            <button class="btn btn-info btn-sm form-control" type="submit">
                                <i class="icon-search bigger-110"></i>
                                Filter
                            </button>
                        </form>

                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover dataTable table-sortable" id="post-grid"  data-sortable-key="order" data-sortable-default="-id">
                    <thead>
                    <tr>
                        <th>操作时间</th>
                        <th>操作</th>
                        <th>被操作人用户名</th>
                        <th>昵称</th>
                        <th>判定规则</th>
                        <th>操作人用户名</th>

                    </tr>
                    </thead>

                    <tbody>
                    <?foreach($pager->items as $item):?>
                        <tr>
                            <td><?= $this->tag->datetime($item->createdAt) ?></td>
                            <td><?= $item->operationName ?></td>
                            <td><?= $item->subject->username ?>(<?= $item->subjectId ?>)</td>
                            <td><?= $item->subject->screenName ?></td>
                            <td><?= $item->subject->spamReasonMap[$item->spamReason] ?></td>
                            <td><?= $item->operator->username ?>(<?= $item->operatorId ?>)</td>
                        </tr>
                    <?endforeach?>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="btn-group">

                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="dataTables_paginate">
                            <?$this->partial("partial/paginator", array(
                                'pagerUrl' => '/admin/useraudit',
                                'pager' => $pager,
                            ))?>
                        </div>
                    </div>
                </div>

            </div><!--/table div-->

        </div><!-- /col-->
    </div><!--row end-->

</div><!-- /.page-content -->
