<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/dashboard">Home</a>
        </li>

        <li>
            <a href="/admin/keyword/index" class="active">Keyword Count</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
                Keyword Count
            </h3>
            <div class="table-header">
                Showing <?=$pager->offset_start?> to <?=$pager->offset_end?> of <?=$pager->total_items?> Items
            </div>

            <div class="table-responsive dataTables_wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-inline">
                            <div class="form-group">
                                <?=$form->render('keyword', array(
                                    'placeholder' => '关键词',
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>
                            <span>
                                <label for="filter-from-limit">Display</label>
                            </span>
                            <div class="form-group">
                                <?=$form->render('limit', array(
                                    'class' => 'form-control input-sm'
                                ))?>
                            </div>

                            <button class="btn btn-info btn-sm form-control" type="submit">
                                <i class="icon-search bigger-110"></i>
                                Filter
                            </button>
                        </form>

                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover dataTable table-sortable" id="post-grid"  data-sortable-key="order" data-sortable-default="-keyword">
                    <thead>
                        <th class="hidden-480">
                            <a href="<?=$this->tag->uri('/admin/keyword/index', $pager->query)?>" class="sortable-link" data-sortable-value="keyword">Keyword</a>
                        </th>
                        <th>
                            <a href="<?=$this->tag->uri('/admin/keyword/index', $pager->query)?>" class="sortable-link" data-sortable-value="count">Count</a>
                        </th>
                        <th class="">该关键词搜到的页面条数</th>
                        <th class=""><a href="<?=$this->tag->uri('/admin/keyword/index', $pager->query)?>" class="sortable-link" data-sortable-value="latestTime">最近一次搜索时间</a></th>
                    </thead>
                    <tbody>
                        <?foreach($data as $item):?>
                                <td><?=$item['keyword'] ?></td>
                                <td><?=$item['count']?></td>
                                <td><?=$item['totalItems'] ?></td>
                                <td><?=$item['latestTime'] ?></td>
                            </tr>
                        <?endforeach?>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-sm-6"></div>
                    <div class="col-sm-6">
                        <div class="dataTables_paginate">
                            <?$this->partial("partial/paginator", array(
                                'pagerUrl' => '/admin/keyword/index',
                                'pager' => $pager,
                            ))?>
                        </div>
                    </div>
                </div>

            </div><!--/table div-->
        </div><!-- /col-->
    </div><!--row end-->

</div><!-- /.page-content -->